server:
  port: 8989
spring:
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.jdbc.mysql.Driver
    url: jdbc:mysql://localhost:3306/lib
    username: 
    password:
    type: 
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
mybatis:
  type-aliases-package: cn.gp1.pojo